apiVersion: v1
kind: Service
metadata:
  name: {{ include "sons-of-the-forest.fullname" . }}
  labels:
    {{- include "sons-of-the-forest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.game }}
      targetPort: game
      protocol: UDP
      name: game
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.game }}
      nodePort: {{ .Values.service.nodePorts.game }}
      {{- end }}
    - port: {{ .Values.service.ports.query }}
      targetPort: query
      protocol: UDP
      name: query
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.query }}
      nodePort: {{ .Values.service.nodePorts.query }}
      {{- end }}
    - port: {{ .Values.service.ports.blobSync }}
      targetPort: blob-sync
      protocol: UDP
      name: blob-sync
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.blobSync }}
      nodePort: {{ .Values.service.nodePorts.blobSync }}
      {{- end }}
  selector:
    {{- include "sons-of-the-forest.selectorLabels" . | nindent 4 }}
