apiVersion: v1
kind: Service
metadata:
  name: {{ include "sons-of-the-forest.fullname" . }}
  labels:
    {{- include "sons-of-the-forest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.ports.game }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.service.ports.query }}
      targetPort: query
      protocol: UDP
      name: query
    - port: {{ .Values.service.ports.blobSync }}
      targetPort: blob-sync
      protocol: UDP
      name: blob-sync
  selector:
    {{- include "sons-of-the-forest.selectorLabels" . | nindent 4 }}
